name: Publish Docker image
on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: npm install and build
        run: |
          npm ci
          npm run build
      - uses: actions/upload-artifact@main
        with:
          name: artifacts
          path: dist/

  test:
    runs-on: ubuntu-latest
    needs: build
    strategy:
      matrix:
        node-version: [15.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - uses: actions/download-artifact@main
        with:
          name: artifacts
          path: dist
      - name: npm install and test
        run: |
          npm install
          npm test

  push_to_registry:
    name: Push Docker image to GitHub Packages
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: check out the repo
        uses: actions/checkout@v2
      - name: set up Docker builder
        uses: docker/setup-buildx-action@v1
      - name: get-npm-version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@master
      - name: log into GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}
      - name: push to Github Container Registry
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: |
            ghcr.io/eddiejaoude/stargate:v${{ steps.package-version.outputs.current-version}}
            ghcr.io/eddiejaoude/stargate:latest
